from pathlib import Path
def tr(path,d):
 p=Path(path); s=p.read_text(encoding='utf-8')
 for a,b in d.items(): s=s.replace(a,b)
 p.write_text(s,encoding='utf-8')
tr('src/components/solutions/SolutionsArchitectureEn.astro',{
'NAPRAVE IN SENZORJI':'DEVICES AND SENSORS','Števci · senzorji · telemetrija':'Meters · sensors · telemetry','POVEZLJIVOST':'CONNECTIVITY','OBSTOJEČI SISTEMI':'EXISTING SYSTEMS','zunanji viri':'external sources','API-INTEGRACIJE':'API INTEGRATIONS','Standardni vmesniki':'Standard interfaces','Arhitektura rešitve: od podatka do odločitve':'Solution architecture: from data to decision','IZBERITE DEL REŠITVE':'CHOOSE A SOLUTION LAYER','Kliknite posamezen korak za podrobnosti.':'Select a step for details.','OD PODATKA DO ODLOČITVE':'FROM DATA TO DECISION','Zajem · obdelava · prikaz':'Acquisition · processing · visualization','Analitika · opozorila · priporočila':'Analytics · alerts · recommendations','ODLOČITEV IN UKREP':'DECISION AND ACTION','Človek ali avtomatizacija':'Person or automation','NOC IN UPRAVLJANE STORITVE':'NOC AND MANAGED SERVICES','Nadzor naprav · povezljivosti · alarmov · podpora':'Device · connectivity · alarm monitoring · support','STALEN NADZOR':'CONTINUOUS MONITORING','CELOTNE REŠITVE':'OF THE ENTIRE SOLUTION','Naprave in senzorji prek povezljivosti v Nexavio. Ločena pot: obstoječi\n    sistemi prek API-integracij v Nexavio. KAI je analitični sloj Nexavie. Iz\n    Nexavie do odločitve in ukrepa. NOC spremlja vse sloje in ni postaja\n    podatkovnega toka.':'Devices and sensors connect to Nexavia. Existing systems connect through API integrations. KAI is Nexavia’s analytics layer. Nexavia supports decisions and action, while NOC monitors every layer.'})
tr('src/components/solutions/SiteChromeEn.astro',{
'footerContent.sl':'footerContent.en','homeNavigation':'homeNavigationEn','import { homeNavigation }':'import { homeNavigationEn }','<Header locale="sl" pathname="/resitve" />':'<Header locale="en" pathname="/en/solutions" />','KUEM – domača stran':'KUEM – home page','Kranj, Slovenija':'Kranj, Slovenia','Navigacija v nogi':'Footer navigation','Zasebnost':'Privacy','Vse pravice pridržane.':'All rights reserved.','href="/en/solutions" lang="en"':'href="/resitve" lang="sl"','>EN<':'>SLO<','href="/"':'href="/en/"','Odpri meni':'Open menu','Zapri meni':'Close menu','Glavna navigacija':'Main navigation','Dogovorite se za predstavitev':'Book a presentation'})
tr('src/components/solutions/SolutionsOverviewEn.astro',{
'Chrome from "./SiteChrome.astro"':'Chrome from "./SiteChromeEn.astro"','Architecture from "./SolutionsArchitecture.astro"':'Architecture from "./SolutionsArchitectureEn.astro"','Panel from "./SolutionExplorerPanel.astro"':'Panel from "./SolutionExplorerPanelEn.astro"','<html lang="sl">':'<html lang="en">','Rešitve | KUEM – Od zajema podatka do upravljane storitve':'Solutions | KUEM – From data acquisition to managed service','Raziščite celotno KUEM rešitev: od naprav in obstoječih sistemov prek Nexavie do odločitev in upravljanih storitev.':'Explore the complete KUEM solution: from devices and existing systems through Nexavia to decisions and managed services.','pathname="/resitve"':'pathname="/en/solutions"','Preskoči na vsebino':'Skip to content','REŠITVE KUEM':'KUEM SOLUTIONS','Od zajema podatka do upravljane storitve.':'From data acquisition to managed service.','Povežemo naprave, komunikacijska omrežja, obstoječe sisteme in\n                podatke v rešitev, ki deluje kot celota.':'We connect devices, communication networks, existing systems and data into a solution that works as a whole.','Pogovorimo se':'Let’s talk','Oglejte si tok podatka':'Explore the data flow','Zaupajo nam':'Trusted by','ZAUPAJO NAM':'TRUSTED BY','KAJ UPORABNIK PRIDOBI':'USER BENEFITS','Manj iskanja podatkov. Več časa za ukrepanje.':'Less time searching for data. More time to act.','PRIMERI IZ PRAKSE':'REAL-WORLD EXAMPLES','Od podatka do konkretnega rezultata.':'From data to a concrete result.','USPEŠNE ZGODBE':'SUCCESS STORIES','Začnimo z enim konkretnim izzivom.':'Let’s start with one concrete challenge.','Izberemo primer uporabe, preverimo razpoložljive podatke in\n                predlagamo izvedljiv prvi korak.':'We select a use case, review the available data and propose a feasible first step.','Dogovorite se za uvodni sestanek':'Book an introductory meeting','href="/#kontakt"':'href="/en/contact"','href="/reference"':'href="/en/references"'})
tr('src/components/solutions/SolutionExplorerPanelEn.astro',{'KORAK 01 / 06':'STEP 01 / 06','Zapri podrobnosti':'Close details','Izberite korak':'Choose a step','Korak':'Step','Zapri':'Close','Naslednji: Povezljivost':'Next: Connectivity','Dogovorite se za predstavitev':'Book a presentation','href="/#kontakt"':'href="/en/contact"'})
tr('src/components/solutions/SolutionStepContentEn.astro',{'Dejanski prikaz Nexavie z zemljevidom naprav, kazalniki in opozorili':'Real Nexavia view with a device map, indicators and alerts','Predogled nadzorne plošče Nexavia':'Nexavia dashboard preview','Od opozorila do ukrepa':'From alert to action','Stanje sistema':'System status','24/7 nadzor':'24/7 monitoring','Naprave · povezljivost · alarmi':'Devices · connectivity · alerts'})
